# =============================================
# 京东商品转链返利插件(JDRebate)配置模板
# =============================================
# 用法：复制此文件为config.toml，并根据需要修改配置
# (适用于插件版本 v1.2.0 及更高版本)
# 开发者：wspzf (原始作者), AI (辅助修改)

[basic]
# 是否启用插件 (true: 启用, false: 禁用)
# enable = true
enable = true

# =============================================
# 京东联盟/折京客API配置 (必须填写)
# =============================================

# 折京客appkey，必填
# 在折京客平台注册后获取：http://www.zhetaoke.com/
appkey = "YOUR_APP_KEY"  # 请替换为您的折京客appkey

# 京东联盟ID，必填
# 在京东联盟注册后获取：https://union.jd.com/
union_id = "YOUR_UNION_ID" # 请替换为您的京东联盟ID

# API接口地址，通常无需修改
# api_url = "http://api.zhetaoke.com:20000/api/open_jing_union_open_promotion_byunionid_get.ashx"

# API附加参数 (通常无需修改)
# signurl=5返回更详细的商品信息，通常无需修改
signurl = "5"

# 短链接生成方式
# chainType=2生成短链接，通常无需修改
chain_type = "2"

# =============================================
# 显示与输出配置
# =============================================

# 是否显示返利金额
# 设置为 true, 会在转链后的消息中尝试显示预计的返利金额。
# 设置为 false, 则不显示返利金额。
show_commission = true

# =============================================
# 群组与用户控制配置
# =============================================

# 群组/用户 控制模式
# 用于控制插件在哪些聊天中生效。
# 可选值:
#   "all":       允许所有群聊和私聊 (默认)。
#   "whitelist": 仅允许在下方 `group_list` 名单中指定的群聊或用户。
#   "blacklist": 允许所有群聊和私聊，但会排除下方 `group_list` 名单中指定的群聊或用户。
group_mode = "all"

# 群组/用户 列表 (配合 whitelist 或 blacklist 模式使用)
# - 如果 group_mode 设置为 "whitelist"，此列表为白名单。
# - 如果 group_mode 设置为 "blacklist"，此列表为黑名单。
# - 如果 group_mode 设置为 "all"，此列表不起作用。
#
# 格式: 列表内为字符串，每个字符串是一个群聊ID (通常以 "@chatroom" 结尾) 或个人微信ID。
# 示例:
# group_list = [
#     "1234567890@chatroom",  # 某个群聊的ID
#     "your_friend_wxid",     # 某个好友的微信ID
#     # "another_group@chatroom",
# ]
group_list = []

# 京东链接匹配正则表达式，通常无需修改
# 该正则表达式用于识别消息中的京东链接
# 在TOML中需要对特殊字符进行转义
# jd_link_pattern = "https?:\\/\\/[^\\s<>]*(?:3\\.cn|jd\\.|jingxi|u\\.jd\\.com)[^\\s<>]+"

# =============================================
# 插件核心功能 (信息参考, 非配置项)
# =============================================
# 1. 自动识别微信群聊和私聊中的京东商品链接。
# 2. 支持处理文本消息和微信内XML卡片形式的商品分享。
# 3. 调用API将链接转换为带有推广返利的链接。
# 4. 可配置是否显示商品名称、价格、优惠券和返利信息等。
# 5. 通过 `group_mode` 和 `group_list` 可灵活控制插件的适用范围。

# =============================================
# 常见问题 (信息参考, 非配置项)
# =============================================
# Q: 无法获取商品信息或转链失败怎么办？
# A: 1. 请务必检查 `appkey` 和 `union_id` 是否已正确填写在 `config.toml` 中，并且是您自己申请的有效密钥。
#    2. 确认您的网络连接正常，可以访问折京客API服务。
#    3. 查看机器人运行日志，其中可能会有更详细的错误提示。
#
# Q: 如何获取群ID或用户微信ID？
# A: 不同机器人框架获取方式可能不同。通常可以在机器人收到消息时，从日志中找到消息来源的ID。
#    群聊ID一般以 "@chatroom" 结尾。
