# =============================================
# 京东商品转链返利插件(JDRebate)配置模板
# =============================================
# 用法：复制此文件为config.toml，并根据需要修改配置
# 版本：1.1.0
# 开发者：wspzf

[basic]
# 是否启用插件
# 设置为true启用插件，false禁用插件
enable = true

# =============================================
# 京东联盟/折京客API配置
# =============================================

# 折京客appkey，必填
# 在折京客平台注册后获取：http://www.zhetaoke.com/
appkey = "你的折京客APPKEY"

# 京东联盟ID，必填
# 在京东联盟注册后获取：https://union.jd.com/
union_id = "你的京东联盟ID"

# API接口地址，通常无需修改
api_url = "http://api.zhetaoke.com:20000/api/open_jing_union_open_promotion_byunionid_get.ashx"

# API附加参数
# signurl=5返回更详细的商品信息，通常无需修改
signurl = "5"

# 短链接生成方式
# chainType=2生成短链接，通常无需修改
chain_type = "2"

# =============================================
# 显示与输出配置
# =============================================

# 是否显示返利金额
# 设置为true显示返利金额，false不显示
show_commission = true

# =============================================
# 群组与正则表达式配置
# =============================================

# 允许使用插件的群组列表
# 只有在列表中的群聊才会触发转链功能
# 添加格式: "群ID@chatroom"
allowed_groups = [
    "12345678901@chatroom", # 示例群组1
    "98765432101@chatroom", # 示例群组2
    # 在此处添加更多群组
]

# 京东链接匹配正则表达式，通常无需修改
# 该正则表达式用于识别消息中的京东链接
# 在TOML中需要对特殊字符进行转义
jd_link_pattern = "https?:\\/\\/[^\\s<>]*(?:3\\.cn|jd\\.|jingxi|u\\.jd\\.com)[^\\s<>]+"

# =============================================
# 插件功能说明
# =============================================
# 1. 本插件可以自动识别群聊中的京东商品链接
# 2. 支持处理文本消息和XML卡片消息中的链接
# 3. 将链接转换为带返利信息的推广链接
# 4. 显示商品名称、价格、优惠券和返利信息等
# 5. 只在允许的群组中自动转链

# =============================================
# 常见问题
# =============================================
# Q: 插件无法识别链接怎么办？
# A: 检查jd_link_pattern正则表达式是否匹配您的链接格式
#
# Q: 无法获取商品信息怎么办？
# A: 检查appkey和union_id是否正确填写
#
# Q: 如何获取群ID？
# A: 可以在群聊中发送测试消息，然后查看日志获取群ID 